Repository WildCodeSchool/orleans-php-202009-project-dfj-location, pull requests merged in 2020-10, with the labels that each got.

#2 init project
  public/assets/css/style.css
  src/View/layout.html.twig
Labels: Reviewed

#24 finalize the part contact and css/responsive
  .travis.yml
  public/assets/css/style.css
  src/View/Home/index.html.twig
Labels: Corrections done, Reviewed

#26 Horaires ok
  public/assets/css/style.css
  src/View/Home/index.html.twig
  src/View/layout.html.twig
Labels: Conflicts resolved, Reviewed

#27 S01 us02 footer
  public/assets/css/style.css
  public/assets/images/facebook.png
  public/assets/images/instagram-symbol.png
  src/View/includes/_footer.html.twig
  src/View/layout.html.twig
Labels: Reviewed

#30 fixed some erros for the pres
  src/View/Home/index.html.twig
Labels: Reviewed

#28 Merge dev to master
  .travis.yml
  public/assets/css/style.css
  public/assets/images/facebook.png
  public/assets/images/instagram-symbol.png
  src/View/Home/index.html.twig
  src/View/includes/_footer.html.twig
  src/View/layout.html.twig
Labels: Reviewed
