Repository WildCodeSchool/orleans-php-202009-project-dfj-location, pull requests merged in 2020-11, with the labels that each got.

#49 S02_US05 correction affichage horaires
  public/assets/css/style.css
  src/View/Home/index.html.twig
Labels: Reviewed

#29 [S01_US01] Made a navbar
  composer.json
  composer.lock
  config/config.php
  public/assets/css/style.css
  public/assets/images/horizontal-logo.png
  public/assets/images/logo-bike.png
  public/assets/images/logo-brand.png
  public/assets/images/logo.png
  public/index.php
  src/Controller/AbstractController.php
  src/Controller/HomeController.php
  src/Controller/ItemController.php
  src/Model/AbstractManager.php
  src/Model/Connection.php
  src/Model/ItemManager.php
  src/View/Home/index.html.twig
  src/View/includes/_navbar.html.twig
  src/View/layout.html.twig
  src/routing.php
Labels: Conflicts resolved, Reviewed

#52 Changes on navbar : 'Nos vélos' list deleted and z-index added
  public/assets/css/style.css
  src/View/includes/_navbar.html.twig
Labels: Reviewed

#53 Weekly merge dev to master
  composer.json
  composer.lock
  config/config.php
  public/assets/css/style.css
  public/assets/images/horizontal-logo.png
  public/assets/images/logo-bike.png
  public/assets/images/logo-brand.png
  public/assets/images/logo.png
  public/index.php
  src/Controller/AbstractController.php
  src/Controller/HomeController.php
  src/Controller/ItemController.php
  src/Model/AbstractManager.php
  src/Model/Connection.php
  src/Model/ItemManager.php
  src/View/Home/index.html.twig
  src/View/includes/_navbar.html.twig
  src/View/layout.html.twig
  src/routing.php
Labels: Reviewed

#54 US15 listing des vélos par catégorie
  public/assets/css/style.css
  public/assets/images/VTT/velo-gravel-trek-checkpoint-al3.jpg
  public/assets/images/VTT/velo-gravel-trek-checkpoint-sl-7.jpg
  public/assets/images/VTT/vtt-eagle.png
  public/assets/images/VTT/vtt-femme.png
  src/Controller/BicycleController.php
  src/Model/BicycleManager.php
  src/View/Bicycle/index.html.twig
Labels: Corrections done, Reviewed

#55 Finished user story
  public/assets/css/style.css
  src/Controller/CategoryController.php
  src/Model/CategoryManager.php
  src/View/Category/index.html.twig
Labels: Corrections done, Reviewed

#56 Fixed size for links and added link for 'Nos vélos'
  public/assets/css/style.css
  src/View/includes/_navbar.html.twig
Labels: Corrections done, Reviewed

#58 S02 us04 map
  public/assets/css/style.css
  src/View/Home/index.html.twig
Labels: Reviewed

#57 finished US_21
  public/VTT/velo-gravel-trek-checkpoint-al3.jpg
  public/VTT/velo-gravel-trek-checkpoint-sl-7.jpg
  public/VTT/vtt-eagle.png
  public/VTT/vtt-femme.png
  public/assets/css/style.css
  src/Controller/HomeController.php
  src/Model/HomeManager.php
  src/View/Home/index.html.twig
Labels: Corrections done, Reviewed

#61 added link to legalMentions
  composer.json
  composer.lock
  grumphp.yml
  src/View/includes/_footer.html.twig
Labels: Reviewed

#85 S03 us33 navbar admin
  public/VTT/velo-gravel-trek-checkpoint-al3.jpg
  public/VTT/velo-gravel-trek-checkpoint-sl-7.jpg
  public/VTT/vtt-eagle.png
  public/VTT/vtt-femme.png
  src/View/includes/_navbarAdmin.html.twig
Labels: Corrections done, Reviewed

#86 S03 us22 legal mentions
  composer.json
  composer.lock
  grumphp.yml
  src/Controller/HomeController.php
  src/View/Home/legal-mentions.html.twig
Labels: Reviewed

#31 add form
  .gitignore
  composer.json
  composer.lock
  database_dfj.sql
  public/assets/css/form.css
  public/assets/css/style.css
  src/Controller/BicycleController.php
  src/Controller/ReservationController.php
  src/Model/AbstractManager.php
  src/Model/BicycleManager.php
  src/Model/ReservationManager.php
  src/View/Reservation/reservation.html.twig
  src/View/Reservation/thanks.html.twig
Labels: Corrections done, Reviewed

#90 Finished user story
  src/Controller/AdminCategoryController.php
  src/Model/CategoryManager.php
  src/View/Admin/addCategory.html.twig
Labels: Reviewed

#94 Merge dev to master
  .github/workflows/main.yml
  .gitignore
  .travis.yml
  composer.json
  composer.lock
  database_dfj.sql
  grumphp.yml
  public/VTT/velo-gravel-trek-checkpoint-al3.jpg
  public/VTT/velo-gravel-trek-checkpoint-sl-7.jpg
  public/VTT/vtt-eagle.png
  public/VTT/vtt-femme.png
  public/assets/css/form.css
  public/assets/css/style.css
  src/Controller/AdminCategoryController.php
  src/Controller/BicycleController.php
  src/Controller/HomeController.php
  src/Controller/ReservationController.php
  src/Model/AbstractManager.php
  src/Model/BicycleManager.php
  src/Model/CategoryManager.php
  src/Model/ReservationManager.php
  src/View/Admin/addCategory.html.twig
  src/View/Home/index.html.twig
  src/View/Home/legal-mentions.html.twig
  src/View/Reservation/reservation.html.twig
  src/View/Reservation/thanks.html.twig
  src/View/includes/_navbarAdmin.html.twig
Labels: Reviewed

#88 S03 us27 charte graphique
  composer.json
  composer.lock
  public/assets/css/style.css
  public/assets/images/facebook.png
  public/assets/images/facebook1.png
  public/assets/images/instagram-symbol.png
  public/assets/images/instagram.png
  src/Controller/ReservationController.php
  src/Model/BicycleManager.php
  src/View/Bicycle/index.html.twig
  src/View/Home/index.html.twig
  src/View/Reservation/reservation.html.twig
  src/View/includes/_footer.html.twig
  src/View/includes/_navbar.html.twig
Labels: Corrections done, Reviewed

#89 S03 us08 admin reservation
  database_dfj.sql
  public/assets/css/style.css
  src/Controller/AdminReservationController.php
  src/Controller/ReservationController.php
  src/Model/BicycleManager.php
  src/Model/ReservationManager.php
  src/View/Admin/index.html.twig
  src/View/Admin/reservation.html.twig
  src/View/layoutAdmin.html.twig
Labels: Reviewed

#95 Merge dev to master
  composer.json
  composer.lock
  database_dfj.sql
  public/assets/css/style.css
  public/assets/images/facebook.png
  public/assets/images/facebook1.png
  public/assets/images/instagram-symbol.png
  public/assets/images/instagram.png
  src/Controller/AdminReservationController.php
  src/Controller/ReservationController.php
  src/Model/BicycleManager.php
  src/Model/ReservationManager.php
  src/View/Admin/index.html.twig
  src/View/Admin/reservation.html.twig
  src/View/Bicycle/index.html.twig
  src/View/Home/index.html.twig
  src/View/Reservation/reservation.html.twig
  src/View/includes/_footer.html.twig
  src/View/includes/_navbar.html.twig
  src/View/layoutAdmin.html.twig
Labels: Reviewed

#91 S03 us13 bikelist
  public/assets/css/style.css
  src/Controller/AdminBicycleController.php
  src/Controller/BicycleController.php
  src/Model/BicycleManager.php
  src/View/Admin/bikes.html.twig
  src/View/Reservation/thanks.html.twig
Labels: Conflicts resolved, Reviewed

#92 first commit of US
  src/Controller/AdminCategoryController.php
  src/Model/CategoryManager.php
  src/View/Admin/indexCategory.html.twig
Labels: Corrections done, Reviewed

#124 US25 form resa regrouper vélos
  src/Controller/ReservationController.php
  src/Model/BicycleManager.php
  src/View/Reservation/reservation.html.twig
Labels: Reviewed

#125 S04 us28 edit category
  src/Controller/AdminCategoryController.php
  src/Model/CategoryManager.php
  src/View/Admin/editCategory.html.twig
Labels: Reviewed

#126 S04 us20 create category fix
  src/View/Admin/addCategory.html.twig
Labels: Reviewed

#128 S04 us01 navbar fix
  public/assets/css/style.css
  src/View/includes/_navbar.html.twig
  src/View/layout.html.twig
Labels: Reviewed

#93 S03 us10 remove bike
  public/assets/css/style.css
  src/Controller/AdminBicycleController.php
  src/Controller/ReservationController.php
  src/Model/BicycleManager.php
  src/Model/ReservationManager.php
  src/View/Admin/bikes.html.twig
Labels: Corrections done, Reviewed

#127 S04 us06 carousel
  public/assets/css/style.css
  public/assets/images/loire1.jpg
  public/assets/images/orleansbynight1.jpg
  public/assets/images/tandem1.jpg
  public/assets/images/vtt1.jpg
  src/View/Home/index.html.twig
Labels: Corrections done, Reviewed

#123 add bike
  public/assets/css/style.css
  src/Controller/AdminBicycleController.php
  src/Model/AdminBicycleManager.php
  src/View/Admin/add-bike.html.twig
Labels: Reviewed

#133 Made link to admin panel
  public/assets/css/style.css
  src/View/includes/_footer.html.twig
Labels: Reviewed

#139 finished double table
  src/View/Admin/index.html.twig
Labels: Reviewed

#134 add a vertical line
  public/assets/css/style.css
  src/View/Home/index.html.twig
Labels: Corrections done, Reviewed

#129 US34 ajout de durée et tarifs form résa
  database_dfj.sql
  public/assets/images/Tandem/velo-tandem-touriste-bleu.png
  public/assets/images/Tandem/velo-tandem.png
  public/assets/images/VTC/VTC-deorro.png
  public/assets/images/VTC/vtc-kalkhoff.png
  public/assets/images/VTC/vtc-ridgeback.png
  public/assets/images/VTC/vtc-trek.png
  public/assets/images/velo_electrique/velo-de-randonnee-electrique.png
  public/assets/images/velo_electrique/velo-de-ville-electrique.png
  public/assets/images/velo_electrique/vtc-electric1.png
  public/assets/images/velo_electrique/vtc-electrique-kalkhoff.png
  src/Controller/ReservationController.php
  src/Model/BicycleManager.php
  src/Model/CategoryManager.php
  src/Model/DurationManager.php
  src/Model/PriceManager.php
  src/Model/ReservationManager.php
  src/View/Reservation/reservation.html.twig
  src/View/Reservation/thanks.html.twig
Labels: Corrections done, Reviewed

#142 add a link
  src/View/Admin/bikes.html.twig
Labels: Reviewed

#143 Made about us user story and added some images
  public/assets/css/style.css
  public/assets/images/Velos.jpg
  public/assets/images/cathedrale1.jpg
  public/assets/images/famille1.jpg
  src/Controller/HomeController.php
  src/View/Home/aboutus.html.twig
  src/View/includes/_navbar.html.twig
Labels: Reviewed

#144 US30 upload image admin ajout vélo
  composer.json
  src/Controller/AdminBicycleController.php
  src/Model/AdminBicycleManager.php
  src/View/Admin/add-bike.html.twig
Labels: Reviewed

#145 S04 us27 charte graphique fix
  public/assets/css/style.css
  public/assets/images/background.jpg
Labels: Reviewed

#146 Dev to Master
  composer.json
  database_dfj.sql
  public/assets/css/style.css
  public/assets/images/Tandem/velo-tandem-touriste-bleu.png
  public/assets/images/Tandem/velo-tandem.png
  public/assets/images/VTC/VTC-deorro.png
  public/assets/images/VTC/vtc-kalkhoff.png
  public/assets/images/VTC/vtc-ridgeback.png
  public/assets/images/VTC/vtc-trek.png
  public/assets/images/Velos.jpg
  public/assets/images/background.jpg
  public/assets/images/cathedrale1.jpg
  public/assets/images/famille1.jpg
  public/assets/images/loire1.jpg
  public/assets/images/orleansbynight1.jpg
  public/assets/images/tandem1.jpg
  public/assets/images/velo_electrique/velo-de-randonnee-electrique.png
  public/assets/images/velo_electrique/velo-de-ville-electrique.png
  public/assets/images/velo_electrique/vtc-electric1.png
  public/assets/images/velo_electrique/vtc-electrique-kalkhoff.png
  public/assets/images/vtt1.jpg
  src/Controller/AdminBicycleController.php
  src/Controller/HomeController.php
  src/Controller/ReservationController.php
  src/Model/AdminBicycleManager.php
  src/Model/BicycleManager.php
  src/Model/CategoryManager.php
  src/Model/DurationManager.php
  src/Model/PriceManager.php
  src/Model/ReservationManager.php
  src/View/Admin/add-bike.html.twig
  src/View/Admin/bikes.html.twig
  src/View/Admin/index.html.twig
  src/View/Home/aboutus.html.twig
  src/View/Home/index.html.twig
  src/View/Reservation/reservation.html.twig
  src/View/Reservation/thanks.html.twig
  src/View/includes/_footer.html.twig
  src/View/includes/_navbar.html.twig
Labels: Reviewed

#130 delete_category finished
  src/Controller/AdminCategoryController.php
  src/Model/CategoryManager.php
  src/View/Admin/indexCategory.html.twig
Labels: Corrections done, Reviewed

#132 S04 us02 footer fix
  public/assets/css/style.css
  src/View/includes/_footer.html.twig
Labels: Conflicts resolved, Reviewed

#135 add a verification
  src/Controller/ReservationController.php
Labels: Corrections done, Reviewed

#141 US35 gestion vélo préselectionné
  src/Controller/ReservationController.php
  src/View/Reservation/reservation.html.twig
Labels: Conflicts resolved, Reviewed

#140 S04 us11 editiondevelo
  src/Controller/AdminBicycleController.php
  src/Model/AdminBicycleManager.php
  src/Model/ReservationManager.php
  src/View/Admin/bikes.html.twig
  src/View/Admin/editor-bike.html.twig
Labels: Corrections done, Reviewed

#147 fixed bootstrap
  src/View/Admin/indexCategory.html.twig
Labels: Reviewed

#148 S05 fixv line
  src/View/Home/index.html.twig
Labels: Reviewed

#149 S05 fix carousel
  src/View/Home/index.html.twig
Labels: Reviewed

#150 S05 icon fix
  src/View/layout.html.twig
  src/View/layoutAdmin.html.twig
Labels: Reviewed

#151 fixed bg-color
  public/assets/css/style.css
Labels: Reviewed

#152 updated Form and fixes
  src/Controller/AdminBicycleController.php
  src/Model/AdminBicycleManager.php
  src/View/Admin/add-bike.html.twig
Labels: Reviewed

#153 finish detailbike
  public/assets/css/style.css
  src/Controller/DetailController.php
  src/Model/BicycleManager.php
  src/View/Bicycle/detailsBike.html.twig
Labels: Corrections done, Reviewed

#175 Fixed issue #162
  src/Model/CategoryManager.php
Labels: Reviewed

#177 Fix issue #160
  src/Controller/AdminBicycleController.php
Labels: Reviewed

#179 fix liens detailvelo
  src/View/Bicycle/index.html.twig
Labels: Reviewed

#180 fixed issues #156 #178
  public/assets/css/style.css
  src/View/includes/_footer.html.twig
Labels: Reviewed

#183 fix function show issue 174
  src/Controller/BicycleController.php
  src/Controller/DetailController.php
Labels: Reviewed

#188 Made a fix on about us section
  public/assets/css/style.css
  src/View/Home/aboutus.html.twig
Labels: Reviewed

#189 fix contact issue165
  src/View/Home/index.html.twig
Labels: Reviewed

#190 Fixed the admin navbar
  src/View/includes/_navbarAdmin.html.twig
Labels: Reviewed

#184 fixed issue #181
  public/assets/css/style.css
Labels: Reviewed

#191 change an image and the display
  public/assets/images/Tandem/velo-tandem.png
  src/View/Bicycle/index.html.twig
Labels: Reviewed

#193 dev to master
  public/assets/css/style.css
  public/assets/images/Tandem/velo-tandem.png
  src/Controller/AdminBicycleController.php
  src/Controller/BicycleController.php
  src/Controller/DetailController.php
  src/Model/CategoryManager.php
  src/View/Bicycle/index.html.twig
  src/View/Home/aboutus.html.twig
  src/View/Home/index.html.twig
  src/View/includes/_footer.html.twig
  src/View/includes/_navbarAdmin.html.twig
Labels: Reviewed

#187 change a placeholder, issue#161
  public/assets/images/Tandem/velo-tandem.png
  src/View/Reservation/reservation.html.twig
Labels: Corrections done, Reviewed

#196 fix detail velo issue192
  public/assets/css/style.css
  src/View/Bicycle/detailsBike.html.twig
Labels: Reviewed

#199 fix link cardnouveauté issue 198
  src/Model/BicycleManager.php
  src/Model/HomeManager.php
  src/View/Home/index.html.twig
Labels: Reviewed

#182 change the carousel
  public/assets/css/style.css
  src/View/Home/index.html.twig
Labels: Conflicts resolved, Reviewed

#194 Fix issue #173
  database_dfj.sql
  public/assets/css/style.css
  public/assets/images/Tandem/velo-tandem-touriste-bleu.png
  public/assets/images/VTC/VTC-deorro.png
  public/assets/images/VTC/vtc-kalkhoff.png
  public/assets/images/VTC/vtc-ridgeback.png
  public/assets/images/VTC/vtc-trek.png
  public/assets/images/VTT/velo-gravel-trek-checkpoint-al3.jpg
  public/assets/images/VTT/velo-gravel-trek-checkpoint-sl-7.jpg
  public/assets/images/VTT/vtt-eagle.png
  public/assets/images/VTT/vtt-femme.png
  public/assets/images/velo_electrique/velo-de-randonnee-electrique.png
  public/assets/images/velo_electrique/velo-de-ville-electrique.png
  public/assets/images/velo_electrique/vtc-electric1.png
  public/assets/images/velo_electrique/vtc-electrique-kalkhoff.png
  public/uploads/.gitignore
  src/Controller/AdminBicycleController.php
  src/Model/AdminBicycleManager.php
  src/View/Admin/add-bike.html.twig
  src/View/Admin/editor-bike.html.twig
  src/View/Bicycle/index.html.twig
  src/View/Home/index.html.twig
Labels: Conflicts resolved, Reviewed

#201 change the background home page
  public/assets/css/home.css
  src/View/Home/index.html.twig
Labels: Corrections done, Reviewed

#203 fix detailvelobutton issue200
  public/assets/css/style.css
  src/Model/BicycleManager.php
  src/View/Bicycle/detailsBike.html.twig
Labels: Corrections done, Reviewed

#205 S05 fix img
  public/assets/css/style.css
  src/View/Bicycle/detailsBike.html.twig
Labels: Reviewed

#206 Finished fix on category buttons
  public/assets/css/style.css
  src/View/Category/index.html.twig
Labels: Corrections done, Reviewed

#207 Merge dev to master
  database_dfj.sql
  public/assets/css/home.css
  public/assets/css/style.css
  public/assets/images/Tandem/velo-tandem-touriste-bleu.png
  public/assets/images/Tandem/velo-tandem.png
  public/assets/images/VTC/VTC-deorro.png
  public/assets/images/VTC/vtc-kalkhoff.png
  public/assets/images/VTC/vtc-ridgeback.png
  public/assets/images/VTC/vtc-trek.png
  public/assets/images/VTT/velo-gravel-trek-checkpoint-al3.jpg
  public/assets/images/VTT/velo-gravel-trek-checkpoint-sl-7.jpg
  public/assets/images/VTT/vtt-eagle.png
  public/assets/images/VTT/vtt-femme.png
  public/assets/images/velo_electrique/velo-de-randonnee-electrique.png
  public/assets/images/velo_electrique/velo-de-ville-electrique.png
  public/assets/images/velo_electrique/vtc-electric1.png
  public/assets/images/velo_electrique/vtc-electrique-kalkhoff.png
  public/uploads/.gitignore
  src/Controller/AdminBicycleController.php
  src/Model/AdminBicycleManager.php
  src/Model/BicycleManager.php
  src/Model/HomeManager.php
  src/View/Admin/add-bike.html.twig
  src/View/Admin/editor-bike.html.twig
  src/View/Bicycle/detailsBike.html.twig
  src/View/Bicycle/index.html.twig
  src/View/Category/index.html.twig
  src/View/Home/index.html.twig
  src/View/Reservation/reservation.html.twig
  src/View/includes/_navbarAdmin.html.twig
Labels: Reviewed

#208 Corrected spelling mistakes, text formatting and some titles
  src/View/Admin/add-bike.html.twig
  src/View/Admin/addCategory.html.twig
  src/View/Admin/bikes.html.twig
  src/View/Admin/editCategory.html.twig
  src/View/Admin/editor-bike.html.twig
  src/View/Admin/index.html.twig
  src/View/Admin/indexCategory.html.twig
  src/View/Admin/reservation.html.twig
  src/View/Bicycle/detailsBike.html.twig
  src/View/Home/index.html.twig
  src/View/Home/legal-mentions.html.twig
  src/View/Reservation/reservation.html.twig
  src/View/Reservation/thanks.html.twig
Labels: Reviewed

#209 Fix suppression vélo
  src/View/Admin/bikes.html.twig
Labels: Reviewed

#210 Merge dev to master
  src/View/Admin/add-bike.html.twig
  src/View/Admin/addCategory.html.twig
  src/View/Admin/bikes.html.twig
  src/View/Admin/editCategory.html.twig
  src/View/Admin/editor-bike.html.twig
  src/View/Admin/index.html.twig
  src/View/Admin/indexCategory.html.twig
  src/View/Admin/reservation.html.twig
  src/View/Bicycle/detailsBike.html.twig
  src/View/Home/index.html.twig
  src/View/Home/legal-mentions.html.twig
  src/View/Reservation/reservation.html.twig
  src/View/Reservation/thanks.html.twig
Labels: Reviewed
